In [ ]:
import re
import requests
import urllib

def word_break(text_br):
    words = re.findall(r'\b\S+\b', text_br) 
    return words

def find_accession(query):
    global K
    K=K+1
    print (K, end="\r")
    ac_uniprot = ""
    id_uniprot = ""
    try:
        res = urllib.request.urlopen("http://www.uniprot.org/uniprot/" + query + ".txt").read()
        s = str(res, 'utf-8')
#         print(s)
#         print(res)
        match_word=word_break(s)
#         print(match_word)
        for i in range(len(match_word)):
#                 print(match_word[i])
                if match_word[i] == "AC":
                    ac_uniprot =  match_word[i+1] 
                    break;
        for i in range(len(match_word)):
                if match_word[i] == "ID":
                    id_uniprot =  match_word[i+1]
                    break;
        return ac_uniprot,id_uniprot
    except urllib.error.HTTPError:
  # Do something here to handle the error. For example:
      print("URL", query, "could not be read.")
      return ac_uniprot,id_uniprot

In [ ]:
K=0
find_accession("P13595")

In [1]:
import pandas as pd
import numpy as np

data_2dge = pd.read_excel('2dge AC ID.xlsx')
data_HRMS = pd.read_excel('HRMS AC ID.xlsx')

In [2]:
data_2dge

,Unnamed: 0,Accession Name,Brain part,AC_uniprot,ID_uniprot
0,0,1433B_MOUSE,"OB, HT, MD",Q9CQV8,1433B_MOUSE
1,1,1433E_MOUSE,"OB, MB, HT, HC, CB, MD",P62259,1433E_MOUSE
2,2,1433F_MOUSE,OB,P68510,1433F_MOUSE
3,3,1433G_MOUSE,"OB, CC, MB, HT, HC, CB, MD",P61982,1433G_MOUSE
4,4,1433T_MOUSE,"OB, MD",P68254,1433T_MOUSE
...,...,...,...,...,...
510,510,VIME_MOUSE,OB,P20152,VIME_MOUSE
511,511,VINC_MOUSE,"OB, CC, MB",Q64727,VINC_MOUSE
512,512,VPS29_MOUSE,"OB, CC, MB",Q9QZ88,VPS29_MOUSE
513,513,WDR1_MOUSE,"OB, CC",O88342,WDR1_MOUSE
514,514,WDR61_MOUSE,OB,Q9ERF3,WDR61_MOUSE

In [23]:
data_HRMS

,Unnamed: 0,Accession,Accession Name,Brain part,AC_uniprot,ID_uniprot
0,0,P16546,SPTN1_MOUSE,"OB, MD, CB, HC, HT, CC",P16546,SPTN1_MOUSE
1,1,P01942,HBA_MOUSE,"OB, MD, CB, HC, HT, CC",P01942,HBA_MOUSE
2,2,Q6PIC6,AT1A3_MOUSE,"OB, MB, MD, CB, HC, HT, CC",Q6PIC6,AT1A3_MOUSE
3,3,P17182,ENOA_MOUSE,"OB, MB, MD, CB, HC, HT, CC",P17182,ENOA_MOUSE
4,4,O08599,STXB1_MOUSE,"OB, MB, MD, CB, HC, HT, CC",O08599,STXB1_MOUSE
...,...,...,...,...,...,...
6298,6298,S4R223,S4R223_MOUSE,MB,S4R223,S4R223_MOUSE
6299,6299,A2AV13,A2AV13_MOUSE,MB,A2AV13,A2AV13_MOUSE
6300,6300,Q6PB99,Q6PB99_MOUSE,MB,Q6PB99,Q6PB99_MOUSE
6301,6301,Q3U3Z4,Q3U3Z4_MOUSE,MB,Q3U3Z4,Q3U3Z4_MOUSE
6302,6302,E9QAT4,E9QAT4_MOUSE,MB,E9QAT4,SC16A_MOUSE

In [19]:
# data.apply(lambda row: check_equal(row), axis=1)

for index, row in data_2dge.iterrows() :
    id_given = row["Accession Name"]
    id_uniprot = row["ID_uniprot"]
    if id_given != id_uniprot:
        print(index,id_given,id_uniprot,row["AC_uniprot"])

27 AIBP_MOUSE NNRE_MOUSE Q8K4Z3
54 PGFS_MOUSE PXL2B_MOUSE Q9DB60
63 CB070_MOUSE F166C_MOUSE Q9DAS2
66 CHCH3_MOUSE MIC19_MOUSE Q9CRB9
74 CLH_MOUSE CLH1_MOUSE Q68FD5
77 CN166_MOUSE RTRAF_MOUSE Q9CQE8
113 DHSA_MOUSE SDHA_MOUSE Q8K2B3
114 DHSB_MOUSE SDHB_MOUSE Q9CQA3
145 ES1_MOUSE GAL3A_MOUSE Q9D172
161 FTHFD_MOUSE AL1L1_MOUSE Q8R0Y6
170 GBB5_MOUSE GNB5_MOUSE P62881
191 GRP78_MOUSE BIP_MOUSE P20029
231 IMMT_MOUSE MIC60_MOUSE Q8CAQ8
323 PDDC1_MOUSE GALD1_MOUSE Q8BFQ8
375 PSD7_MOUSE PSMD7_MOUSE P26516
424 SIRT2_MOUSE SIR2_MOUSE Q8VDQ8
435 SPTA2_MOUSE SPTN1_MOUSE P16546
445 SYG_MOUSE GARS_MOUSE Q9CZD3
462 TBB2C_MOUSE TBB4B_MOUSE P68372
464 TBB4_MOUSE TBB4A_MOUSE Q9D6F9

In [87]:
# # data.apply(lambda row: check_equal(row), axis=1)

# for index, row in data_HRMS.iterrows() :
#     id_given = row["Accession Name"]
#     id_uniprot = row["ID_uniprot"]
#     if id_given != id_uniprot:
#         print(index,id_given,id_uniprot,row["AC_uniprot"])

73 KCC1D_MOUSE DE Q8BW96
139 F213A_MOUSE PXL2A_MOUSE Q9CYH2
211 NCAM1_MOUSE in P13595
216 GRP78_MOUSE BIP_MOUSE P20029
435 nan IDHP_MOUSE P54071
438 ILVBL_MOUSE HACL2_MOUSE Q8BU33
479 GPX41_MOUSE GPX4_MOUSE O70325
508 nan DUS3L_MOUSE Q91XI1
551 FA49A_MOUSE CYRIA_MOUSE Q8BHZ0
575 PGFS_MOUSE PXL2B_MOUSE Q9DB60
584 PRPTZ_MOUSE PTPRZ_MOUSE B9EKR1
595 CG043_MOUSE MA11_MOUSE Q3UTZ3
627 ASNA_MOUSE GET3_MOUSE O54984
831 nan PCKGM_MOUSE Q8BH04
962 41_MOUSE EPB41_MOUSE P48193
1047 ARHL2_MOUSE ADPRS_MOUSE Q8CG72
1187 CJ035_MOUSE F241B_MOUSE Q9D882
1226 CP062_MOUSE VP35L_MOUSE Q8BWQ6
1367 ES1_MOUSE GAL3A_MOUSE Q9D172
1380 F192A_MOUSE PIP30_MOUSE Q91WE2
1381 F198B_MOUSE GAK1B_MOUSE Q3UPI1
1382 FA45A_MOUSE DEN10_MOUSE Q9D8N2
1383 FA49B_MOUSE CYRIB_MOUSE Q921M7
1465 nan GPDA_MOUSE P13707
1506 HNRPD_MOUSE in Q60668
1553 K1211_MOUSE CRACD_MOUSE Q5PR69
1554 K1468_MOUSE RELCH_MOUSE Q148V7
1664 nan MICA3_MOUSE Q8CJ19
1668 nan MMSA_MOUSE Q9EQ20
1734 NIBAN_MOUSE NIBA1_MOUSE Q3UW53
1792 PCSK1_MOUSE PCS1N_MOUSE Q9QXV0
2110 SYHC_MOUSE HARS1_MOUSE Q61035
2134 TBRG4_MOUSE FAKD4_MOUSE Q91YM4
2431 ELAV2_MOUSE 3'UTR Q60899
2565 CA123_MOUSE CZIB_MOUSE Q8BHG2
2677 FA69A_MOUSE DIK1A_MOUSE Q9D6I7
2755 KDEL1_MOUSE PLGT2_MOUSE Q9JHP7
2798 MTSSL_MOUSE MTSS2_MOUSE Q6P9S0
2853 PCIF1_MOUSE CAPAM_MOUSE P59114
2972 ST5_MOUSE DEN2B_MOUSE Q924W7
3012 TMM56_MOUSE TLCD4_MOUSE Q8CGF5
3192 MRRP1_MOUSE TM10C_MOUSE Q3UFY8
3209 GRM1B_MOUSE ASTRB_MOUSE Q80TI0
3489 C43BP_MOUSE CERT_MOUSE Q9EQG9
3508 CI172_MOUSE AJM1_MOUSE A2AJA9
3509 CJ107_MOUSE CBCO1_MOUSE Q8CDT7
3512 CK065_MOUSE MFI_MOUSE Q9D4W2
3519 CO052_MOUSE CCD9B_MOUSE A3KGF9
3531 CQ053_MOUSE HROB_MOUSE Q32P12
3538 CX021_MOUSE TASL_MOUSE Q9D3J9
3544 DFNA5_MOUSE GSDME_MOUSE Q9Z2D3
3556 DUS27_MOUSE STYL2_MOUSE Q148W8
3649 K0556_MOUSE KATIP_MOUSE Q8C753
3718 MUM1_MOUSE PWP3A_MOUSE Q6DID5
3724 MF4B3_MOUSE
3837 SCHI1_MOUSE
4025 CD022_MOUSE CF299_MOUSE Q810M1
4046 CS057_MOUSE BRME1_MOUSE Q6DIA7
4072 ETBR2_MOUSE G37L1_MOUSE Q99JG2
4073 F198A_MOUSE GAK1A_MOUSE Q3UY90
4173 NIBL1_MOUSE NIBA2_MOUSE Q8R1F1
4196 nan PDP1_MOUSE Q3UV70
4325 ABCB8_MOUSE MITOS_MOUSE Q9CXJ4
4437 GPR98_MOUSE AGRV1_MOUSE Q8VHN7
4457 K1324_MOUSE ELAP1_MOUSE A2AFS3
4612 VKIND_MOUSE KNDC1_MOUSE Q0KK55
4633 CALM_MOUSE
4663 SOGA2_MOUSE MTCL1_MOUSE Q3UHU5
4671 nan BCKD_MOUSE O55028
4673 CN166_MOUSE RTRAF_MOUSE Q9CQE8
4681 CNIH_MOUSE CNIH1_MOUSE O35372
4726 CCD51_MOUSE MITOK_MOUSE Q3URS9
4738 CO027_MOUSE TM266_MOUSE Q8BZB3
4767 F105A_MOUSE OTULL_MOUSE Q3TVP5
4769 F179B_MOUSE TGRM1_MOUSE Q6A070
4771 F208A_MOUSE TASOR_MOUSE Q69ZR9
4773 F8I2_MOUSE HAP40_MOUSE Q00558
4802 CC037_MOUSE HMCES_MOUSE Q8R1M0
4818 K1239_MOUSE NWD2_MOUSE Q6P5U7
4821 K226L_MOUSE PACER_MOUSE Q3TD16
4837 MIMIT_MOUSE NDUF2_MOUSE Q59J78
4848 NAL9B_MOUSE NLR9B_MOUSE Q66X22
4900 RN219_MOUSE OBI1_MOUSE Q8K2Y0
4953 TMM8A_MOUSE PGAP6_MOUSE Q9ESN3
4980 F6VME3_MOUSE
4998 S4R1F9_MOUSE
5001 S4R2H6_MOUSE
5013 J3KMM5_MOUSE
5015 G3X9L6_MOUSE
5037 Q32ME1_MOUSE AT2B4_MOUSE Q6Q477
5040 F8WIX8_MOUSE
5057 Q80WS9_MOUSE
5058 A2A860_MOUSE WBP2_MOUSE P97765
5087 G3XA10_MOUSE HNRPU_MOUSE Q8VEK3
5091 G3UWG1_MOUSE
5094 D3Z7R1_MOUSE
5111 D3YVN7_MOUSE
5178 D3YW48_MOUSE A0A0R4IZW8_MOUSE A0A0R4IZW8
5195 A0A067XG52_MOUSE
5220 B9EJ80_MOUSE PDZD8_MOUSE B9EJ80
5241 A2AU89_MOUSE TP53B_MOUSE P70399
5243 Q0VGU4_MOUSE VGF_MOUSE Q0VGU4
5264 E9PVS1_MOUSE
5296 E9PZA8_MOUSE SYT7_MOUSE Q9R0N7
5297 Q99K47_MOUSE FIBA_MOUSE E9PV24
5298 E9Q769_MOUSE
5305 TMM35_MOUSE TM35A_MOUSE Q9D328
5341 D3YX79_MOUSE
5357 G3X9N6_MOUSE OSBL8_MOUSE B9EJ86
5367 E9Q070_MOUSE
5387 H3BK93_MOUSE
5390 E9Q8K9_MOUSE
5410 G3UZK4_MOUSE
5444 E9Q1X1_MOUSE
5476 E9PZT1_MOUSE
5493 H3BK79_MOUSE
5497 Q99LT1_MOUSE
5512 B1AWN6_MOUSE SCN2A_MOUSE B1AWN6
5515 D3Z607_MOUSE
5536 E9PW30_MOUSE
5559 nan E0CXN5_MOUSE E0CXN5
5591 E9PUX4_MOUSE
5604 D3YXQ8_MOUSE
5607 A2APX7_MOUSE SCN1A_MOUSE A2APX8
5650 D3Z3B2_MOUSE
5670 G5E920_MOUSE
5700 E9QPW8_MOUSE
5708 E9Q3T0_MOUSE
5721 Q5SVE1_MOUSE
5735 A3KGQ6_MOUSE
5742 J3QNB0_MOUSE
5787 LARGE_MOUSE LARG1_MOUSE Q9Z1M7
5798 NRROS_MOUSE LRC33_MOUSE Q8BMT4
5846 A2CG28_MOUSE NOTC4_MOUSE P31695
5864 D3Z4B8_MOUSE
5887 E9PYH6_MOUSE SET1A_MOUSE E9PYH6
5899 Q3UW66_MOUSE THTM_MOUSE Q99J99
5920 D5MNX2_MOUSE
5925 F6U6W2_MOUSE
5928 D3YUM8_MOUSE
5942 Q9JIS2_MOUSE KLK4_MOUSE Q9Z0M1
5945 F6SVV1_MOUSE
5953 F6UYF1_MOUSE
5965 V9GXG1_MOUSE SLN14_MOUSE V9GXG1
5994 F6ZZL0_MOUSE
5995 F7D5W0_MOUSE
6002 M0QWY5_MOUSE
6029 E9Q8S5_MOUSE
6054 E9Q8F1_MOUSE
6067 E9PUV7_MOUSE CFA54_MOUSE Q8C6S9
6108 J3QP68_MOUSE
6117 Q3TDH6_MOUSE TXTP_MOUSE Q8JZU2
6144 A2AAU3_MOUSE
6153 Q3TFD0_MOUSE GLYM_MOUSE Q9CZN7
6166 E0CZ24_MOUSE
6173 Q3V3S8_MOUSE 2A5B_MOUSE Q6PD28
6182 D3Z2Q7_MOUSE HMCN1_MOUSE D3YXG0
6204 D6RDE2_MOUSE
6239 nan D6RIL6_MOUSE D6RIL6
6277 F6UIT9_MOUSE
6293 D3YXV0_MOUSE
6302 E9QAT4_MOUSE SC16A_MOUSE E9QAT4

In [21]:
data_2dge[data_2dge["ID_uniprot"].duplicated(keep=False)]

Empty DataFrame
Columns: [Unnamed: 0, Accession Name, Brain part, AC_uniprot, ID_uniprot]
Index: []

In [79]:
ids = data["ID_uniprot"]
data_2dge[ids.isin(ids[ids.duplicated()])]

Empty DataFrame
Columns: [Unnamed: 0, Accession Name, Brain part, AC_uniprot, ID_uniprot]
Index: []

In [249]:
data_2dge_final = data_2dge.drop(['Unnamed: 0'], axis=1)

## Preparation of HRMS data

In [100]:
# data.apply(lambda row: check_equal(row), axis=1)
K=0
for index, row in data_HRMS.iterrows() :
    ac_given = row["Accession"]
    ac_uniprot = row["AC_uniprot"]
    # double check for the non equal
    if ac_given != ac_uniprot:
#         print(index,ac_given,ac_uniprot,row["ID_uniprot"])
        ac_uniprot,id_uniprot = find_accession(row["Accession"])
#     print(ac_uniprot,id_uniprot)
        data_HRMS.loc[index, 'AC_uniprot'] = ac_uniprot
        data_HRMS.loc[index, 'ID_uniprot'] = id_uniprot
    id_uniprot = row["ID_uniprot"]
    id_given = row["Accession Name"]
    # 2 id_uniprot was equal to "in" so we fix it 
    if id_uniprot=="in":
        ac_uni,id_uni = find_accession(row["Accession"])
        data_HRMS.loc[index, 'ID_uniprot'] = id_uni
        print(id_given,ac_uniprot,id_uniprot,id_uni)

NCAM1_MOUSE P13595 in NCAM1_MOUSE
HNRPD_MOUSE Q60668 in HNRPD_MOUSE
URL Q3TI53 could not be read.
URL P62204 could not be read.

In [101]:
data_HRMS.to_excel("HRMS AC ID modified.xlsx")

In [102]:
data_HRMS_modified = pd.read_excel('HRMS AC ID modified.xlsx')

In [103]:
data_HRMS_modified = data_HRMS_modified.drop(['Unnamed: 0', 'Unnamed: 0.1'], axis=1)

In [104]:
# data.apply(lambda row: check_equal(row), axis=1)
l=0
o=0
obsolete = []
import math
for index, row in data_HRMS_modified.iterrows() :
    ac_given = row["Accession"]
    ac_uniprot = row["AC_uniprot"]
    if ac_given != ac_uniprot:
        l = l+1
#         print(index,ac_given,ac_uniprot,row["ID_uniprot"])
    if pd.isnull(ac_uniprot):
        o = o+1
        obsolete.append(index)
print(l,o)
print("Obsolete entries: "+str(o))

71 53
Obsolete entries: 53

In [147]:
data_HRMS_no_obsolete = data_HRMS_modified.drop(obsolete)

In [148]:
data_HRMS_no_obsolete

,Accession,Accession Name,Brain part,AC_uniprot,ID_uniprot
0,P16546,SPTN1_MOUSE,"OB, MD, CB, HC, HT, CC",P16546,SPTN1_MOUSE
1,P01942,HBA_MOUSE,"OB, MD, CB, HC, HT, CC",P01942,HBA_MOUSE
2,Q6PIC6,AT1A3_MOUSE,"OB, MB, MD, CB, HC, HT, CC",Q6PIC6,AT1A3_MOUSE
3,P17182,ENOA_MOUSE,"OB, MB, MD, CB, HC, HT, CC",P17182,ENOA_MOUSE
4,O08599,STXB1_MOUSE,"OB, MB, MD, CB, HC, HT, CC",O08599,STXB1_MOUSE
...,...,...,...,...,...
6298,S4R223,S4R223_MOUSE,MB,S4R223,S4R223_MOUSE
6299,A2AV13,A2AV13_MOUSE,MB,A2AV13,A2AV13_MOUSE
6300,Q6PB99,Q6PB99_MOUSE,MB,Q6PB99,Q6PB99_MOUSE
6301,Q3U3Z4,Q3U3Z4_MOUSE,MB,Q3U3Z4,Q3U3Z4_MOUSE
6302,E9QAT4,E9QAT4_MOUSE,MB,E9QAT4,SC16A_MOUSE

#### Check for duplicates

In [149]:
duplicates = data_HRMS_no_obsolete[data_HRMS_no_obsolete["ID_uniprot"].duplicated(keep=False)]

In [150]:
# 12 proteins was concidered unique in midbrain but after their name being changed they are not any more
# the only duplicates are the proteins that belong only in the midbrain
duplicates

     Accession Accession Name              Brain part AC_uniprot   ID_uniprot
79      Q6Q477    AT2B4_MOUSE          OB, HC, HT, CC     Q6Q477  AT2B4_MOUSE
281     P97765     WBP2_MOUSE  OB, MD, CB, HC, HT, CC     P97765   WBP2_MOUSE
607     Q8VEK3    HNRPU_MOUSE  OB, MD, CB, HC, HT, CC     Q8VEK3  HNRPU_MOUSE
636     B9EJ86    OSBL8_MOUSE          OB, HC, HT, CC     B9EJ86  OSBL8_MOUSE
667     A2APX8    SCN1A_MOUSE      OB, MD, HC, HT, CC     A2APX8  SCN1A_MOUSE
2121    Q9R0N7     SYT7_MOUSE      OB, MD, CB, HT, CC     Q9R0N7   SYT7_MOUSE
2157    Q99J99     THTM_MOUSE  OB, MD, CB, HC, HT, CC     Q99J99   THTM_MOUSE
2295    Q9Z0M1     KLK4_MOUSE              OB, MD, HT     Q9Z0M1   KLK4_MOUSE
2299    Q6PD28     2A5B_MOUSE                  OB, HT     Q6PD28   2A5B_MOUSE
2307    P70399    TP53B_MOUSE              OB, CB, HT     P70399  TP53B_MOUSE
2430    Q8JZU2     TXTP_MOUSE                  HC, MD     Q8JZU2   TXTP_MOUSE
3310    E9PV24     FIBA_MOUSE              CC, MD, HT     E9PV24   FIBA_MOUSE
5037    Q32ME1   Q32ME1_MOUSE                      MB     Q6Q477  AT2B4_MOUSE
5058    A2A860   A2A860_MOUSE                      MB     P97765   WBP2_MOUSE
5087    G3XA10   G3XA10_MOUSE                      MB     Q8VEK3  HNRPU_MOUSE
5241    A2AU89   A2AU89_MOUSE                      MB     P70399  TP53B_MOUSE
5296    E9PZA8   E9PZA8_MOUSE                      MB     Q9R0N7   SYT7_MOUSE
5297    Q99K47   Q99K47_MOUSE                      MB     E9PV24   FIBA_MOUSE
5357    G3X9N6   G3X9N6_MOUSE                      MB     B9EJ86  OSBL8_MOUSE
5607    A2APX7   A2APX7_MOUSE                      MB     A2APX8  SCN1A_MOUSE
5899    Q3UW66   Q3UW66_MOUSE                      MB     Q99J99   THTM_MOUSE
5942    Q9JIS2   Q9JIS2_MOUSE                      MB     Q9Z0M1   KLK4_MOUSE
6117    Q3TDH6   Q3TDH6_MOUSE                      MB     Q8JZU2   TXTP_MOUSE
6173    Q3V3S8   Q3V3S8_MOUSE                      MB     Q6PD28   2A5B_MOUSE

In [151]:
dup = []
for index, row in data_HRMS_no_obsolete.iterrows() :
    if row["ID_uniprot"] in duplicates.values:
        if row["Brain part"]=="MB":
            dup.append(index)
        else:
            data_HRMS_no_obsolete.loc[index, 'Brain part'] = data_HRMS_no_obsolete.loc[index, 'Brain part']+", MB"

In [152]:
dup

[5037, 5058, 5087, 5241, 5296, 5297, 5357, 5607, 5899, 5942, 6117, 6173]

In [154]:
data_HRMS_final= data_HRMS_no_obsolete.drop(dup)

In [155]:
data_HRMS_final

,Accession,Accession Name,Brain part,AC_uniprot,ID_uniprot
0,P16546,SPTN1_MOUSE,"OB, MD, CB, HC, HT, CC",P16546,SPTN1_MOUSE
1,P01942,HBA_MOUSE,"OB, MD, CB, HC, HT, CC",P01942,HBA_MOUSE
2,Q6PIC6,AT1A3_MOUSE,"OB, MB, MD, CB, HC, HT, CC",Q6PIC6,AT1A3_MOUSE
3,P17182,ENOA_MOUSE,"OB, MB, MD, CB, HC, HT, CC",P17182,ENOA_MOUSE
4,O08599,STXB1_MOUSE,"OB, MB, MD, CB, HC, HT, CC",O08599,STXB1_MOUSE
...,...,...,...,...,...
6298,S4R223,S4R223_MOUSE,MB,S4R223,S4R223_MOUSE
6299,A2AV13,A2AV13_MOUSE,MB,A2AV13,A2AV13_MOUSE
6300,Q6PB99,Q6PB99_MOUSE,MB,Q6PB99,Q6PB99_MOUSE
6301,Q3U3Z4,Q3U3Z4_MOUSE,MB,Q3U3Z4,Q3U3Z4_MOUSE
6302,E9QAT4,E9QAT4_MOUSE,MB,E9QAT4,SC16A_MOUSE

In [158]:
ids = data_HRMS_final["AC_uniprot"]
data_HRMS_final[ids.isin(ids[ids.duplicated()])]
# NO DUPLICATES

Empty DataFrame
Columns: [Accession, Accession Name, Brain part, AC_uniprot, ID_uniprot]
Index: []

In [159]:
data_HRMS_final.to_excel("HRMS final.xlsx")

### data_HRMS_final data_2dge_final

These tables have ALL the correct information

In [265]:
d_HRMS = data_HRMS_final.drop(['Accession', 'Accession Name'], axis=1)

In [266]:
d_2dge = data_2dge_final.drop(['Accession Name'], axis=1)

In [287]:
# belong to d_HRMS and doesn't belong to d_2dge
d_HRMS_unique = d_HRMS[~d_HRMS['AC_uniprot'].isin(d_2dge ['AC_uniprot'])]
d_HRMS_unique = d_HRMS_unique.rename(columns={"Brain part": "Brain part HRMS"})
print("Unique in HRMS: " + str(len(d_HRMS_unique)))
# belong to d_2dge and doesn't belong to d_HRMS
d_2dge_unique = d_2dge[~d_2dge['AC_uniprot'].isin(d_HRMS ['AC_uniprot'])]
d_2dge_unique = d_2dge_unique.rename(columns={"Brain part": "Brain part 2dge"})
print("Unique in 2dge: " + str(len(d_2dge_unique)))
common = pd.merge(d_2dge, d_HRMS, on=["AC_uniprot","ID_uniprot"])
print("Common: " + str(len(common)))
total_prot = pd.concat([d_HRMS_unique,d_2dge_unique,common])
total_prot.to_excel("Total proteins.xlsx")

Unique in HRMS: 5771
Unique in 2dge: 48
Common: 467

In [288]:
total_prot

,Brain part HRMS,AC_uniprot,ID_uniprot,Brain part 2dge,Brain part_x,Brain part_y
8,"OB, MD, CB, HC, HT, CC",P14873,MAP1B_MOUSE,NaN,NaN,NaN
13,"OB, MB, MD, CB, HC, HT, CC",P20357,MTAP2_MOUSE,NaN,NaN,NaN
17,"OB, MB, MD, CB, HC, HT, CC",Q62261,SPTB2_MOUSE,NaN,NaN,NaN
18,"OB, MD, CB, HC, HT, CC",Q6PIE5,AT1A2_MOUSE,NaN,NaN,NaN
19,"OB, MB, MD, CB, HC, HT, CC",Q91ZZ3,SYUB_MOUSE,NaN,NaN,NaN
...,...,...,...,...,...,...
462,NaN,P20152,VIME_MOUSE,NaN,OB,"OB, MB, MD, CB, HC, HT"
463,NaN,Q64727,VINC_MOUSE,NaN,"OB, CC, MB","OB, MB, MD, CB, HC, HT, CC"
464,NaN,Q9QZ88,VPS29_MOUSE,NaN,"OB, CC, MB","OB, MD, HC, HT, CC"
465,NaN,O88342,WDR1_MOUSE,NaN,"OB, CC","OB, MD, CB, HC, HT, CC"
466,NaN,Q9ERF3,WDR61_MOUSE,NaN,OB,"OB, MD, HC, HT"

In [317]:
cellular_component = pd.DataFrame(columns=['AC_uniprot', 'ID_uniprot', 'gene_id','information'])
molecular_function = pd.DataFrame(columns=['AC_uniprot', 'ID_uniprot', 'gene_id','information'])
biological_process = pd.DataFrame(columns=['AC_uniprot', 'ID_uniprot', 'gene_id','information'])

In [318]:
# data.apply(lambda row: check_equal(row), axis=1)
K=0
total_prot1 = total_prot.copy()
for index, row in total_prot1.iterrows() :
    ac_uniprot = row["AC_uniprot"]
    id_uniprot = row["ID_uniprot"]
    cc,mf,bp,cc_id,mf_id,bp_id = retrieve_prot_inf(ac_uniprot)
    cc_len = len(cc)
    mf_len = len(mf)
    bp_len = len(bp)
    for i in range(cc_len):
        cellular_component = cellular_component.append({'AC_uniprot': ac_uniprot,'ID_uniprot':id_uniprot,'gene_id':cc_id[i],'information':cc[i]}, ignore_index=True)
    for i in range(mf_len):
        molecular_function = molecular_function.append({'AC_uniprot': ac_uniprot,'ID_uniprot':id_uniprot,'gene_id':mf_id[i],'information':mf[i]}, ignore_index=True)
    for i in range(bp_len):
        biological_process = biological_process.append({'AC_uniprot': ac_uniprot,'ID_uniprot':id_uniprot,'gene_id':bp_id[i],'information':bp[i]}, ignore_index=True)

In [326]:
biological_process

,AC_uniprot,ID_uniprot,gene_id,information
0,P14873,MAP1B_MOUSE,GO:0048675,axon extension
1,P14873,MAP1B_MOUSE,GO:0007409,axonogenesis
2,P14873,MAP1B_MOUSE,GO:0009987,cellular process
3,P14873,MAP1B_MOUSE,GO:0071363,cellular response to growth factor stimulus
4,P14873,MAP1B_MOUSE,GO:0071375,cellular response to peptide hormone stimulus
...,...,...,...,...
44020,Q9ERF3,WDR61_MOUSE,GO:0045638,negative regulation of myeloid cell differenti...
44021,Q9ERF3,WDR61_MOUSE,GO:0051571,positive regulation of histone H3-K4 methylation
44022,Q9ERF3,WDR61_MOUSE,GO:2001162,positive regulation of histone H3-K79 methylation
44023,Q9ERF3,WDR61_MOUSE,GO:0006368,transcription elongation from RNA polymerase I...
44024,Q9ERF3,WDR61_MOUSE,GO:0016055,Wnt signaling pathway

In [328]:
cellular_component.to_excel("cellular component.xlsx")

In [329]:
molecular_function.to_excel("molecular function.xlsx")

In [330]:
biological_process.to_excel("biological process.xlsx")

In [335]:
ppppppp = pd.read_excel('biological process.xlsx')

In [336]:
ppppppp[ppppppp["AC_uniprot"]=="P14873"]

,Unnamed: 0,AC_uniprot,ID_uniprot,gene_id,information
0,0,P14873,MAP1B_MOUSE,GO:0048675,axon extension
1,1,P14873,MAP1B_MOUSE,GO:0007409,axonogenesis
2,2,P14873,MAP1B_MOUSE,GO:0009987,cellular process
3,3,P14873,MAP1B_MOUSE,GO:0071363,cellular response to growth factor stimulus
4,4,P14873,MAP1B_MOUSE,GO:0071375,cellular response to peptide hormone stimulus
5,5,P14873,MAP1B_MOUSE,GO:0016358,dendrite development
6,6,P14873,MAP1B_MOUSE,GO:0021700,developmental maturation
7,7,P14873,MAP1B_MOUSE,GO:0061162,establishment of monopolar cell polarity
8,8,P14873,MAP1B_MOUSE,GO:0051915,induction of synaptic plasticity by chemical s...
9,9,P14873,MAP1B_MOUSE,GO:0001578,microtubule bundle formation
10,10,P14873,MAP1B_MOUSE,GO:0000226,microtubule cytoskeleton organization
11,11,P14873,MAP1B_MOUSE,GO:0007017,microtubule-based process
12,12,P14873,MAP1B_MOUSE,GO:0047497,mitochondrion transport along microtubule
13,13,P14873,MAP1B_MOUSE,GO:0032387,negative regulation of intracellular transport
14,14,P14873,MAP1B_MOUSE,GO:0007026,negative regulation of microtubule depolymeriz...
15,15,P14873,MAP1B_MOUSE,GO:0014012,peripheral nervous system axon regeneration
16,16,P14873,MAP1B_MOUSE,GO:0045773,positive regulation of axon extension
17,17,P14873,MAP1B_MOUSE,GO:0031116,positive regulation of microtubule polymerization
18,18,P14873,MAP1B_MOUSE,GO:0045666,positive regulation of neuron differentiation
19,19,P14873,MAP1B_MOUSE,GO:0031114,regulation of microtubule depolymerization
20,20,P14873,MAP1B_MOUSE,GO:0009743,response to carbohydrate
21,21,P14873,MAP1B_MOUSE,GO:0042493,response to drug
22,22,P14873,MAP1B_MOUSE,GO:0032355,response to estradiol
23,23,P14873,MAP1B_MOUSE,GO:0010035,response to inorganic substance
24,24,P14873,MAP1B_MOUSE,GO:0017085,response to insecticide
25,25,P14873,MAP1B_MOUSE,GO:0009612,response to mechanical stimulus
26,26,P14873,MAP1B_MOUSE,GO:0033189,response to vitamin A
27,27,P14873,MAP1B_MOUSE,GO:0007416,synapse assembly

In [327]:
molecular_function[molecular_function["information"]=="actin binding"]

      AC_uniprot   ID_uniprot     gene_id    information
0         P14873  MAP1B_MOUSE  GO:0003779  actin binding
6         P20357  MTAP2_MOUSE  GO:0003779  actin binding
12        Q62261  SPTB2_MOUSE  GO:0003779  actin binding
51        Q9WV92  E41L3_MOUSE  GO:0003779  actin binding
106       Q9QYR6  MAP1A_MOUSE  GO:0003779  actin binding
...          ...          ...         ...            ...
19906     Q8CC35  SYNPO_MOUSE  GO:0003779  actin binding
19913     O55042   SYUA_MOUSE  GO:0003779  actin binding
20069     Q9JKK7  TMOD2_MOUSE  GO:0003779  actin binding
20083     P58771   TPM1_MOUSE  GO:0003779  actin binding
20204     O88342   WDR1_MOUSE  GO:0003779  actin binding

[160 rows x 4 columns]

In [315]:
import re
import requests
import urllib

def word_break(text_br):
    words = re.findall(r'\b\S+\b', text_br) 
    return words

def retrieve_prot_inf(query):
    global K
    K=K+1
    print (query,"  ---  ", K, end="\r")
    ac_uniprot = ""
    id_uniprot = ""
    res = urllib.request.urlopen("http://www.uniprot.org/uniprot/" + query + ".txt").read()
    s = str(res, 'utf-8')
#     print(s)
    lines = s.splitlines()
#     print(lines)
#   print(res)
    cellular_comp = [] #C
    molecular_func = [] #F
    biological_proc = [] #P
    cellular_comp_id = [] #C
    molecular_func_id = [] #F
    biological_proc_id = [] #P
    
    for i in range(len(lines)):
        match_word=word_break(lines[i])
        if len(lines[i])>2:
            if match_word[0]=="DR" and match_word[1]=="GO":
#                 print(lines[i])
#                 print(match_word)
#                 print(len(match_word))
#                 print(len(match_word)-5)
#                 print("-------------------------------")
                gene_id = match_word[2]
                
                if match_word[3][0] == "C":
#                     print(match_word[3][2:])
                    sentence = match_word[3][2:]
                    #because we must exclude DR GO GO:342552 and the first and last word
                    for j in range(4,len(match_word)-1):
                        sentence = sentence +" "+ match_word[j]
                    cellular_comp.append(sentence)
                    cellular_comp_id.append(gene_id)
                elif match_word[3][0] == "F":
#                     print(match_word)
#                     print(match_word[3][2:])
                    sentence = match_word[3][2:]
                    #because we must exclude DR GO GO:342552 and the first and last word
                    for j in range(4,len(match_word)-1):
                        sentence = sentence +" "+ match_word[j]
                    molecular_func.append(sentence)
                    molecular_func_id.append(gene_id)
                elif match_word[3][0] == "P":
#                     print(match_word[3][2:])
                    sentence = match_word[3][2:]
                    #because we must exclude DR GO GO:342552 and the first and last word
                    for j in range(4,len(match_word)-1):
                        sentence = sentence +" "+ match_word[j]
                    biological_proc.append(sentence)
                    biological_proc_id.append(gene_id)
                
    return cellular_comp,molecular_func,biological_proc,cellular_comp_id,molecular_func_id,biological_proc_id

In [316]:
K=0
retrieve_prot_inf("CV028_MOUSE")

(['cytoplasm',
  'cytosol',
  'endoplasmic reticulum membrane',
  'intracellular membrane-bounded organelle',
  'nuclear envelope',
  'nucleoplasm',
  'nucleus',
  'tRNA-splicing ligase complex'],
 ['GTP binding',
  'metal ion binding',
  'RNA ligase ATP activity',
  'vinculin binding'],
 ['in utero embryonic development',
  'placenta development',
  "tRNA exon ligation utilizing 2',3 cyclic phosphate of 5'-exon as source of linkage phosphate",
  'tRNA splicing via endonucleolytic cleavage and ligation'],
 ['GO:0005737',
  'GO:0005829',
  'GO:0005789',
  'GO:0043231',
  'GO:0005635',
  'GO:0005654',
  'GO:0005634',
  'GO:0072669'],
 ['GO:0005525', 'GO:0046872', 'GO:0003972', 'GO:0017166'],
 ['GO:0001701', 'GO:0001890', 'GO:0000971', 'GO:0006388'])